FROM bitnami/spark:3.4.2

USER root

# Install Python3, pip, and necessary libraries
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean

# Install Python dependencies
RUN pip3 install numpy pandas scikit-learn pyspark==3.4.2

USER 1001